export const ON_FETCH_FEED_DATA_LOADING = 'ON_FETCH_FEED_DATA_LOADING';
export const ON_FETCH_FEED_DATA_SUCCESS = 'ON_FETCH_FEED_DATA_SUCCESS';
export const ON_FETCH_FEED_DATA_FAILURE = 'ON_FETCH_FEED_DATA_FAILURE';
